######################## default configuration ####################
baseURL = "https://examplesite.org/"
title = "Advant Calender"
theme = "advant"


############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

[permalinks]
  posts = '/:year/:month/:title/'
